version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      
  app:
    depends_on: 
      - "postgres"
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/onebitexchange
    ports:
      - "3000:3000"